### ISSUE TITLE
Panic on ConsumerGroup.Consume() error

### ISSUE THREAD

**Issue by billygout** [Shopify/sarama#2381]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
|v.1.24.0  | 2.5.0 |1.18.2  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

`read tcp [<REDACTED>]:58236->[<REDACTED>]:9093: i/o timeout`

##### Problem Description
During a network maintenance when connectivity between consumers and kafka was temporarily unavailable, my application crashed with a log.Fatalf() call, displaying  the error shown above (`i/o timeout`). The `log.Fatalf()` call is placed in a `for` loop followed the pattern found in sarama's provided consumer group example, as shown below:
https://github.com/Shopify/sarama/blob/610514edec1825240d59b62e4d7f1aba4b1fa000/examples/consumergroup/main.go#L104-L116

Question: Is it advisable to place in a production app the `log.Fatalf()` call in the same way as is found in the example shown above? Assuming a temporary network outage occurs, would it be better to simply log the Consume() error and continue to the next loop iteration in order to try calling Consume() again, hopefully successfully? Or does Consume() only ever return a non-nil error when in an unrecoverable state and thus exiting the program is the best recourse?

**Comment by billygout** [comment]
Hi @dnwe, could you perhaps help me find someone to answer this question? thanks!

**Comment by billygout** [comment]
Hi @dnwe, this remains an issue for me. Can you please advise? thanks!

**Comment by dnwe** [comment]
@billygout hmm, yes I’m surprised the example code has a Fatal here, whilst the client does attempt to resolve recoverable errors with a few attempts, the Consume call can return an err here if (e.g.,) metadata failed to refresh within the configured max attempts so it would be more sensible to log or metric based on the error type

**Comment by billygout** [comment]
hi @dnwe, thank you for your response. This issue is still a problem for me, and I'm not sure what the error types may be here. Can you please advise further on that or let me know if there are plans to update the example? Thanks!

**Comment by david-bergman** [comment]
thanks @dnwe , I will do that, my issue is with the consumer, on the consumergroup consume() method, I have implemented a code change now with a set of staggered retries in the loop on an error, where it continues instead of breaking out the loop, basically calling the consume method again even after the initial error. I will raise a separate issue if this does not resolve it on my end.

**Comment by billygout** [comment]
@david-bergman Can you please let us know whether your changes are known to be working? If so, perhaps you can share them so that they may be worked into the example (https://github.com/IBM/sarama/blob/main/examples/consumergroup/main.go)? Thanks!

**Comment by billygout** [comment]
@dnwe Could we please keep this open until the consumergroup example may be updated per best practices?

**Comment by billygout** [comment]
@david-bergman thanks for sharing. I don't know the answer to the question. Also, I note that the `log.Panicf` is still present in the latest code at the time of this posting: https://github.com/IBM/sarama/blob/d4dc7bcff59ae890d90746b8b5fe257e6a7caa57/examples/exactly_once/main.go#L136

**Comment by Gezi-lzq** [comment]
I have the same question, shouldn't we stop retrying to consume when the service is having issues?

**Comment by dnwe** [comment]
Believe to be fixed by ConsumeClaim impl correction
